name: ShopStream CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_NAME: shopstream_db
      DB_USER: admin1
      DB_PASSWORD: dummy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r api/requirements.txt

      - name: Run tests
        run: |
          pytest -v
